DECLARE
		vENAME EMP.ENAME%TYPE;
		vJOB   	EMP.JOB%TYPE;

		CURSOR cEMP(vDEPTNO EMP.DEPTNO%TYPE) IS SELECT ENAME,JOB FROM EMP WHERE DEPTNO = vDEPTNO;

BEGIN
	OPEN cEMP(&DEPTNO);
	LOOP
		FETCH cEMP INTO vENAME,vJOB;
		EXIT WHEN cEMP%NOTFOUND;
		IF cEMP%FOUND THEN
				DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME      JOB');
				DBMS_OUTPUT.PUT_LINE(vENAME || '         '||vJOB);
		END IF;
	END LOOP;

	CLOSE cEMP;

	END;
	/