DECLARE
    vEMPNO   EMP.EMPNO%TYPE;
    vENAME   EMP.ENAME%TYPE;
    vSAL     EMP.SAL%TYPE;
    vGRADE   SALGRADE.GRADE%TYPE;
BEGIN
    SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
    INTO   vEMPNO, vENAME, vSAL, vGRADE
    FROM   EMP E, SALGRADE S
    WHERE  E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND    E.EMPNO = &EMPNO;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO:- ' || vEMPNO);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME:- ' || vENAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE SALARY:- ' || vSAL);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE GRADE:- ' || vGRADE);
END;
/
