DECLARE
    vEMPNO   EMP.EMPNO%TYPE;
    vENAME   EMP.ENAME%TYPE;
    vSAL     EMP.SAL%TYPE;
    vGRADE   SALGRADE.GRADE%TYPE;
     VDNAME  DEPT.DNAME%TYPE;
BEGIN
    SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE, D.DNAME
    INTO   vEMPNO, vENAME, vSAL, vGRADE, vDNAME
    FROM   EMP E, SALGRADE S, DEPT D
    WHERE  E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND E.DEPTNO = D.DEPTNO
    AND    E.EMPNO = &EMPNO;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NO:- ' || vEMPNO);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME:- ' || vENAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE SALARY:- ' || vSAL);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE GRADE:- ' || vGRADE);
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME:-' ||vDNAME);
END;
/
