--DELETE RECORD AND CHECK SUCESS--
	
	BEGIN
		DELETE FROM STUDENT WHERE ROLLNO = 101;

	IF SQL%ROWCOUNT = 0 THEN
		DBMS_OUTPUT.PUT_LINE('no record deleted');
	ELSE
		DBMS_OUTPUT.PUT_LINE('record deleted');
	END IF;
END;
	/