--UPDATE WITH CONDITION USING SQL%FOUND
	
BEGIN
	UPDATE STUDENT SET SUB1 = SUB1+5 WHERE SUB1 <40;
	
	IF SQL%FOUND THEN
		DBMS_OUTPUT.PUT_LINE('marks updated for weak students');
	END IF;
END;
/
