DECLARE
	NAME VARCHAR2(10);
	GENDER CHAR(1);
BEGIN
	NAME :='&NAME';
	GENDER:=UPPER('&GENDER');
	IF GENDER='M' THEN
			DBMS_OUTPUT.PUT_LINE('WELCOME MR' ||NAME);
	ELSIF GENDER='F' THEN
			DBMS_OUTPUT.PUT_LINE('WELCOME MS' ||NAME);
	ELSE
			DBMS_OUTPUT.PUT_LINE('WRONG INPUT');
	END IF;

END;
/