DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM STUDENT
    WHERE SUB1 > 35;

    DBMS_OUTPUT.PUT_LINE(
        'TOTAL NUMBER OF STUDENTS WHO SCORED MORE THAN 35 IN SUB1 : ' || v_count
    );
END;
/

// student table 

CREATE TABLE STUDENT (
    ROLLNO NUMBER PRIMARY KEY,
    NAME   VARCHAR2(30),
    SUB1   NUMBER
);



INSERT INTO STUDENT VALUES (1, 'ARUN', 40);
INSERT INTO STUDENT VALUES (2, 'KIRAN', 30);
INSERT INTO STUDENT VALUES (3, 'MEENA', 55);
INSERT INTO STUDENT VALUES (4, 'RAJU', 35);
INSERT INTO STUDENT VALUES (5, 'ANITA', 70);

COMMIT;
